### ISSUE TITLE
Order multiple products but OrderDetails only insert the lastest record

### ISSUE THREAD

**Issue by vutuanminh34** [mubassir-hasan/EcommerceMvc#1]
Hi hasan, as I said yesterday, I tried to fix the NewOrder (NewOrderViewModel model) method in the OrderController so that when ordering, all products are in OrderDetail. Currently, I really want to fix this bug but have not succeeded yet. Would you mind spending a little time trying to figure it out for me? Thank you so muchh!

**Comment by mubassir-hasan** [comment]
master updated can you check?

**Comment by vutuanminh34** [comment]
Wonderful. Thanks to you I got to know this bug come from migration. Big thumbs up for you!
