### ISSUE TITLE
Management orderDetailAdmin

### ISSUE THREAD

**Issue by vutuanminh34** [mubassir-hasan/EcommerceMvc#2]
It's embarrassing to bother you again. The order manager you updated to project yesterday means a lot to me. And I see that you have enabled order status management but I can't find a view of OrderStatusAdmin to manage the status for each order. Could you spend another a moment out of the day to create a view of OrderStatusAdmin for me? I really thank you for that.
![OrderStatusAdmin_request](https://user-images.githubusercontent.com/69794301/112665154-54d96b80-8e8d-11eb-8631-90aaefa70992.png)

**Comment by mubassir-hasan** [comment]
added status option in order details pleasee check

**Comment by vutuanminh34** [comment]
I checked and it works. Thanks you very much!!!! You are so enthusiastic that you have been helping me for the past week.
